name: demo-client

executables:
  demo-client:
    main: Main.hs
    source-dirs:
      - ./.
      - ../src
    dependencies:
      - base
      - generics-eot
      - reflex-dom
      - generics-sop
      - string-conversions
      - aeson-pretty
