flags: {}

packages:
  - location: ./.
  - location:
      git: https://github.com/ryantrinkle/reflex
      commit: 784f9f79396ae713a03fc4d81f8a67b75d6ade1c # need a few package bumps not present in hackage release yet
    extra-dep: true
  - location:
      git: https://github.com/ryantrinkle/reflex-dom
      commit: a60ae687cdc284a8eb3776fc95aa2adefc51e7ec # hamishmack-master (improved-base compatible)
    extra-dep: true
#   - location:
#       git: https://github.com/haskell-servant/servant
#       commit: d2d25954c3bbd04a9bddadf8d3abd8a57488aa33
#     subdirs:
#       - servant
#       - servant-client
#     extra-dep: true
#   - location: /home/shahn/src/crdt-tree-vector
#     extra-dep: true

resolver: lts-3.10

compiler: ghcjs-0.2.0.20151001_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151001_ghc-7.10.2:
        url: "https://github.com/fizruk/ghcjs/releases/download/v0.2.0.20151001/ghcjs-0.2.0.20151001.tar.gz"

extra-deps:
  - generics-eot-0.2.1
  - markdown-unlit-0.4.0
#  - http-api-data-0.1.1.1
  - ref-tf-0.4
  - these-0.6.1.0
  - ghcjs-dom-0.2.2.0 # improved-base compatible with (2015-10-01 ghcjs)
