dependencies:
  - base == 4.*
  - generics-eot
  - servant-server

executables:
  demo-cli:
    main: demo-cli.hs
    source-dirs:
      - src
    dependencies:
      - getopt-generics

  demo-server:
    main: demo-server.hs
    source-dirs:
      - drivers
      - src
    dependencies:
      - wai-ghcjs
      - warp
      - logging-facade
      - wai
      - getopt-generics
      - string-conversions
      - http-types
      - transformers
      - filepath
      - swagger2
      - interpolate
      - lens
      - aeson
      - swagger
      - servant-swagger
      - basic-sop

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - hspec-wai
